//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDepartmentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeDepartmentDetail()
        {
            this.TicketRequests = new HashSet<TicketRequest>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual DepartmentList DepartmentList { get; set; }
        public virtual EmployeeList EmployeeList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketRequest> TicketRequests { get; set; }
    }
}
